services:
  rabbitmq:
    image: rabbitmq:4-management

    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
      - "${RABBITMQ_MQTT_PORT}:1883"

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins:ro

volumes:
  rabbitmq_data: